# Generated by Django 5.1.2 on 2024-11-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wrapped", "0002_customuser_account_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="wrapped",
            name="color",
            field=models.CharField(default="000000", max_length=6),
            preserve_default=False,
        ),
    ]
