# Generated by Django 5.1.2 on 2024-10-26 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0002_spotifyauthdata_spotifyprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='auth_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='wrapped.spotifyauthdata'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='spotify_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='wrapped.spotifyprofile'),
        ),
    ]
