# Generated by Django 5.1.2 on 2024-10-29 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0003_alter_customuser_auth_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_name_set',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='auth_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='wrapped.spotifyauthdata'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='spotify_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='wrapped.spotifyprofile'),
        ),
    ]
