# Generated by Django 5.1.2 on 2024-12-05 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wrapped", "0003_wrapped_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="DancePanel",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("wrapped.panel",),
        ),
        migrations.CreateModel(
            name="GamePanel",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("wrapped.panel",),
        ),
        migrations.CreateModel(
            name="IntroPanel",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("wrapped.panel",),
        ),
        migrations.CreateModel(
            name="LLMPanel",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("wrapped.panel",),
        ),
        migrations.CreateModel(
            name="PreGamePanel",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("wrapped.panel",),
        ),
        migrations.CreateModel(
            name="PreLlmPanel",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("wrapped.panel",),
        ),
        migrations.CreateModel(
            name="TopGenresPanel",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("wrapped.panel",),
        ),
        migrations.CreateModel(
            name="TopTracksPanel",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("wrapped.panel",),
        ),
        migrations.RemoveField(
            model_name="panel",
            name="type",
        ),
    ]
