# Generated by Django 5.1.2 on 2024-11-16 05:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wrapped", "0004_wrapped_date_created_wrapped_name_wrapped_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="album",
        ),
        migrations.RemoveField(
            model_name="artist",
            name="albums",
        ),
        migrations.RemoveField(
            model_name="artist",
            name="songs",
        ),
        migrations.RemoveField(
            model_name="song",
            name="artists",
        ),
        migrations.CreateModel(
            name="Panel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("IN", "Intro"),
                            ("TT", "Top Tracks"),
                            ("PL", "Pre Llm"),
                            ("LM", "Llm"),
                            ("TG", "Top Genres"),
                            ("PG", "Pre Game"),
                            ("GM", "Game"),
                            ("DC", "Dance"),
                        ],
                        default="TT",
                        max_length=2,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                (
                    "wrapped",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="panels",
                        to="wrapped.wrapped",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "unique_together": {("wrapped", "order")},
            },
        ),
        migrations.DeleteModel(
            name="Album",
        ),
        migrations.DeleteModel(
            name="Artist",
        ),
        migrations.DeleteModel(
            name="Song",
        ),
    ]
