# Generated by Django 5.1.2 on 2024-12-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wrapped", "0004_dancepanel_gamepanel_intropanel_llmpanel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="panel",
            name="type",
            field=models.CharField(
                choices=[
                    ("IN", "Intro"),
                    ("TT", "Top Tracks"),
                    ("PL", "Pre Llm"),
                    ("LM", "Llm"),
                    ("TG", "Top Genres"),
                    ("PG", "Pre Game"),
                    ("GM", "Game"),
                    ("DC", "Dance"),
                ],
                default="IN",
                max_length=2,
            ),
            preserve_default=False,
        ),
    ]
