# Generated by Django 5.1.2 on 2024-10-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0004_customuser_is_name_set_alter_customuser_auth_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_name_set',
            field=models.BooleanField(default=False),
        ),
    ]
