# Generated by Django 5.1.2 on 2024-10-29 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0005_alter_customuser_is_name_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_name_set',
        ),
    ]
