name: Super-Linter

on:
  pull_request:
    paths:
      - "backend/wrapped/**"
      - "frontend/src/**"
  push:
    paths:
      - "backend/wrapped/**"
      - "frontend/src/**"

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          FILTER_REGEX_INCLUDE: "^(backend/wrapped/|frontend/src/).*"
